# Generated by Django 4.0.1 on 2022-05-09 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('dedline', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancel', 'Cancel')], default='active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Work_tables',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.worker')),
            ],
        ),
    ]
